import { trpc } from "@/lib/trpc";
import { ArrowLeftRight, Landmark } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export function FinancePanel({ branchId, mode }: { branchId?: number; mode: "reports" | "treasury" | "accounts" }) {
  const utils = trpc.useUtils();
  const report = trpc.finance.report.useQuery({ branchId: branchId ?? 0 }, { enabled: Boolean(branchId) });
  const accounts = trpc.sales.cashAccounts.useQuery({ branchId: branchId ?? 0 }, { enabled: Boolean(branchId) });
  const [fromCashAccountId, setFrom] = useState<number | undefined>();
  const [toCashAccountId, setTo] = useState<number | undefined>();
  const [amount, setAmount] = useState("");
  const transfer = trpc.finance.transfer.useMutation({ onSuccess: () => { utils.finance.report.invalidate(); utils.sales.cashAccounts.invalidate(); setAmount(""); toast.success("تم تنفيذ التحويل الداخلي"); }, onError: error => toast.error(error.message || "تعذر تنفيذ التحويل") });
  if (!branchId) return <section className="erp-panel empty-state">جارٍ تحديد الفرع...</section>;
  const data = report.data;
  return <section className="finance-layout"><section className="kpi-grid"><article className="kpi-card kpi-card--blue"><div><p>إجمالي المبيعات</p><strong>{((data?.sales ?? 0) / 100).toLocaleString("ar-EG")} <small>ج.م</small></strong><span>{data?.invoices ?? 0} فواتير</span></div></article><article className="kpi-card kpi-card--mint"><div><p>أرصدة الخزن والبنوك</p><strong>{((data?.cashBalance ?? 0) / 100).toLocaleString("ar-EG")} <small>ج.م</small></strong><span>الرصيد المتاح</span></div></article><article className="kpi-card kpi-card--rose"><div><p>الذمم المدينة</p><strong>{((data?.outstanding ?? 0) / 100).toLocaleString("ar-EG")} <small>ج.م</small></strong><span>المبالغ الآجلة</span></div></article><article className="kpi-card kpi-card--indigo"><div><p>وحدات المخزون</p><strong>{(data?.inventoryUnits ?? 0).toLocaleString("ar-EG")}</strong><span>رصيد وحدات الفرع</span></div></article></section><section className="erp-panel finance-accounts"><div className="panel-title"><span><Landmark size={16} />الخزن والبنوك والمحافظ</span></div><table className="erp-table records-table"><thead><tr><th>الحساب</th><th>النوع</th><th>الرصيد الافتتاحي</th><th>الرصيد الحالي</th><th>الحالة</th></tr></thead><tbody>{accounts.data?.map(account => <tr key={account.id}><td>{account.name}</td><td>{account.type}</td><td className="amount">{(account.openingBalance / 100).toLocaleString("ar-EG")} ج.م</td><td className="amount">{(account.currentBalance / 100).toLocaleString("ar-EG")} ج.م</td><td><span className="status-chip status-chip--available">نشط</span></td></tr>)}</tbody></table></section>{mode === "treasury" && <section className="erp-panel transfer-form"><div className="panel-title"><span><ArrowLeftRight size={16} />تحويل داخلي</span></div><label>من حساب<select value={fromCashAccountId ?? ""} onChange={event => setFrom(event.target.value ? Number(event.target.value) : undefined)}><option value="">اختر الحساب المصدر</option>{accounts.data?.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>إلى حساب<select value={toCashAccountId ?? ""} onChange={event => setTo(event.target.value ? Number(event.target.value) : undefined)}><option value="">اختر الحساب المستهدف</option>{accounts.data?.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>المبلغ (ج.م)<input type="number" value={amount} onChange={event => setAmount(event.target.value)} /></label><button className="erp-button erp-button--green" onClick={() => { if (!fromCashAccountId || !toCashAccountId || !amount) return toast.error("أكمل بيانات التحويل"); transfer.mutate({ branchId, fromCashAccountId, toCashAccountId, amount: Math.round(Number(amount) * 100) }); }}>تنفيذ التحويل</button></section>}</section>;
}
