import { trpc } from "@/lib/trpc";
import { CheckCircle2, Copy, MonitorSmartphone, Network, Router, Server } from "lucide-react";
import { toast } from "sonner";

export function NetworkPanel() {
  const status = trpc.network.status.useQuery(undefined, { refetchInterval: 15000 });
  const copy = (value: string) => { navigator.clipboard?.writeText(value); toast.success("تم نسخ عنوان الاتصال"); };
  return <section className="network-layout"><section className="erp-panel network-hero"><div><span className="network-hero__icon"><Network size={25} /></span><h2>الشبكة والربط المحلي</h2><p>إدارة خادم ERP المحلي وعناوين الاتصال للأجهزة داخل نفس شبكة المحل.</p></div><span className="network-status"><CheckCircle2 size={14} />الخدمة تعمل</span></section><section className="network-grid"><article className="erp-panel network-card"><Server size={18} /><span>اسم الخادم</span><strong>{status.data?.hostname ?? "جارٍ الفحص"}</strong><small>وضع التشغيل: {status.data?.mode === "production" ? "محلي / إنتاج" : "تطوير"}</small></article><article className="erp-panel network-card"><Router size={18} /><span>المضيف والمنفذ</span><strong>{status.data ? `${status.data.bindHost}:${status.data.servicePort}` : "—"}</strong><small>الخادم يستمع على المضيف المحدد للشبكة المحلية.</small></article><article className="erp-panel network-card"><MonitorSmartphone size={18} /><span>الأجهزة المتصلة</span><strong>{status.data?.clients.length ?? 0} جلسات نشطة</strong><small>تحديث تلقائي كل 15 ثانية.</small></article></section><section className="erp-panel network-addresses"><div className="panel-title"><span><Router size={16} />عناوين الشبكة المحلية</span><span>{status.data?.addresses.length ?? 0} عناوين</span></div>{status.data?.addresses.length ? <div className="address-list">{status.data.addresses.map(item => { const url = `http://${item.address}:${status.data?.servicePort ?? 3000}`; return <article key={`${item.name}-${item.address}`}><div><strong>{item.name}</strong><span>{url}</span><small>قناع الشبكة: {item.netmask}</small></div><button onClick={() => copy(url)} aria-label="نسخ عنوان الشبكة"><Copy size={15} /></button></article>; })}</div> : <div className="network-empty">لا يظهر عنوان LAN في النسخة المستضافة. بعد تشغيل حزمة ERP على جهازك سيظهر عنوان الجهاز المحلي هنا.</div>}</section><section className="erp-panel network-clients"><div className="panel-title"><span><MonitorSmartphone size={16} />جلسات الشبكة النشطة</span><span>{status.data?.clients.length ?? 0}</span></div>{status.data?.clients.length ? <div className="client-list">{status.data.clients.map(client => <div key={client.address}><strong>{client.address}</strong><span>{client.lastPath} · آخر نشاط: {new Date(client.lastSeenAt).toLocaleTimeString("ar-EG")}</span></div>)}</div> : <div className="network-empty">لا توجد جلسات مرصودة بعد. ستظهر الأجهزة عند فتح ERP محلياً عبر عنوان الشبكة.</div>}</section><section className="erp-panel network-steps"><h3>طريقة الربط داخل المحل</h3><ol><li>شغّل حزمة ERP المحلية على الجهاز الرئيسي.</li><li>تأكد أن أجهزة الكاشير متصلة بنفس Wi‑Fi أو السويتش.</li><li>افتح عنوان الشبكة الظاهر أعلاه من أي متصفح على الجهاز أو الهاتف.</li><li>لا تفتح المنفذ للإنترنت العام؛ استخدمه داخل الشبكة المحلية فقط.</li></ol></section></section>;
}
