import { trpc } from "@/lib/trpc";
import { Building2, Plus, Save, Warehouse } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export function OrganizationManager({ view }: { view: "branches" | "settings" }) {
  const utils = trpc.useUtils();
  const branchesQuery = trpc.organization.branches.useQuery();
  const settingsQuery = trpc.organization.settings.useQuery();
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [color, setColor] = useState("#214696");
  const [settingsForm, setSettingsForm] = useState<{ businessName: string; address: string; taxNumber: string; vatEnabled: boolean; vatRateBps: number; receiptPromoText: string; receiptPromoUrl: string; receiptFormat: "58mm" | "80mm" | "a4"; theme: "light" | "dark" | "navy"; loyaltyEnabled: boolean }>({ businessName: "", address: "", taxNumber: "", vatEnabled: true, vatRateBps: 1400, receiptPromoText: "", receiptPromoUrl: "", receiptFormat: "80mm", theme: "navy", loyaltyEnabled: false });
  useEffect(() => { const item = settingsQuery.data; if (item) setSettingsForm({ businessName: item.businessName, address: item.address ?? "", taxNumber: item.taxNumber ?? "", vatEnabled: Boolean(item.vatEnabled), vatRateBps: item.vatRateBps, receiptPromoText: item.receiptPromoText ?? "", receiptPromoUrl: item.receiptPromoUrl ?? "", receiptFormat: item.receiptFormat, theme: item.theme, loyaltyEnabled: Boolean(item.loyaltyEnabled) }); }, [settingsQuery.data]);
  const createBranch = trpc.organization.createBranch.useMutation({ onSuccess: () => { utils.organization.branches.invalidate(); setName(""); setCode(""); toast.success("تم إنشاء الفرع والمخزن والخزنة الافتراضية"); }, onError: error => toast.error(error.message || "يلزم الدخول كمدير لإنشاء فرع") });
  const updateSettings = trpc.organization.updateSettings.useMutation({ onSuccess: () => { utils.organization.settings.invalidate(); toast.success("تم حفظ إعدادات المؤسسة"); }, onError: error => toast.error(error.message || "تعذر حفظ الإعدادات") });
  if (view === "settings") return <section className="organization-layout"><section className="erp-panel settings-form"><div className="panel-title"><span><Save size={16} />إعدادات المؤسسة والفاتورة</span></div><div className="settings-grid"><label>اسم المؤسسة<input value={settingsForm.businessName} onChange={event => setSettingsForm({ ...settingsForm, businessName: event.target.value })} /></label><label>العنوان<input value={settingsForm.address} onChange={event => setSettingsForm({ ...settingsForm, address: event.target.value })} /></label><label>الرقم الضريبي<input value={settingsForm.taxNumber} onChange={event => setSettingsForm({ ...settingsForm, taxNumber: event.target.value })} /></label><label>معدل الضريبة (نقطة أساس)<input type="number" value={settingsForm.vatRateBps} onChange={event => setSettingsForm({ ...settingsForm, vatRateBps: Number(event.target.value) })} /></label><label>رسالة QR على الفاتورة<input value={settingsForm.receiptPromoText} onChange={event => setSettingsForm({ ...settingsForm, receiptPromoText: event.target.value })} /></label><label>رابط QR الترويجي<input value={settingsForm.receiptPromoUrl} onChange={event => setSettingsForm({ ...settingsForm, receiptPromoUrl: event.target.value })} /></label><label>صيغة الفاتورة<select value={settingsForm.receiptFormat} onChange={event => setSettingsForm({ ...settingsForm, receiptFormat: event.target.value as "58mm" | "80mm" | "a4" })}><option value="58mm">حراري 58mm</option><option value="80mm">حراري 80mm</option><option value="a4">A4</option></select></label><label>المظهر<select value={settingsForm.theme} onChange={event => setSettingsForm({ ...settingsForm, theme: event.target.value as "light" | "dark" | "navy" })}><option value="navy">كحلي</option><option value="light">نهاري</option><option value="dark">ليلي</option></select></label><label className="settings-check"><input type="checkbox" checked={settingsForm.vatEnabled} onChange={event => setSettingsForm({ ...settingsForm, vatEnabled: event.target.checked })} />تفعيل القيمة المضافة</label><label className="settings-check"><input type="checkbox" checked={settingsForm.loyaltyEnabled} onChange={event => setSettingsForm({ ...settingsForm, loyaltyEnabled: event.target.checked })} />تفعيل نقاط الولاء</label></div><button className="erp-button erp-button--green" onClick={() => updateSettings.mutate(settingsForm)} disabled={updateSettings.isPending}>حفظ الإعدادات</button></section></section>;
  return <section className="organization-layout"><section className="erp-panel branch-list"><div className="panel-title"><span><Building2 size={16} />الفروع والمستودعات</span><span>{branchesQuery.data?.length ?? 0} فروع</span></div><div className="branch-cards">{branchesQuery.data?.map(branch => <article key={branch.id} className="branch-card"><span style={{ backgroundColor: branch.color }} /><div><strong>{branch.name}</strong><small>{branch.code} · {branch.address ?? "بدون عنوان"}</small></div><b>{branch.isActive ? "نشط" : "موقوف"}</b></article>)}</div></section><section className="erp-panel branch-form"><div className="panel-title"><span><Plus size={16} />إضافة فرع جديد</span></div><label>اسم الفرع<input value={name} onChange={event => setName(event.target.value)} placeholder="مثال: فرع الملابس" /></label><label>رمز الفرع<input value={code} onChange={event => setCode(event.target.value.toUpperCase())} placeholder="CLOTH" /></label><label>لون الفرع<input type="color" value={color} onChange={event => setColor(event.target.value)} /></label><button className="erp-button erp-button--green" disabled={!name || !code || createBranch.isPending} onClick={() => createBranch.mutate({ name, code, color })}>إنشاء الفرع</button><p>ينشئ النظام تلقائياً مستودعاً وخزنة افتراضيين لهذا الفرع.</p></section></section>;
}
