import { trpc } from "@/lib/trpc";
import { RotateCcw } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export function ReturnsPage({ branchId }: { branchId?: number }) {
  const utils = trpc.useUtils();
  const invoicesQuery = trpc.sales.invoices.useQuery({ branchId: branchId ?? 0 }, { enabled: Boolean(branchId) });
  const accountsQuery = trpc.sales.cashAccounts.useQuery({ branchId: branchId ?? 0 }, { enabled: Boolean(branchId) });
  const [invoiceId, setInvoiceId] = useState<number | undefined>();
  const detailsQuery = trpc.sales.invoiceDetails.useQuery({ invoiceId: invoiceId ?? 0 }, { enabled: Boolean(invoiceId) });
  const [quantities, setQuantities] = useState<Record<number, number>>({});
  const [reason, setReason] = useState("");
  const [refundAccountId, setRefundAccountId] = useState<number | undefined>();
  useEffect(() => { if (detailsQuery.data) setQuantities(Object.fromEntries(detailsQuery.data.items.map(item => [item.id, 0]))); }, [detailsQuery.data]);
  const issueReturn = trpc.sales.return.useMutation({ onSuccess: result => { utils.sales.invoices.invalidate(); utils.commerce.inventory.invalidate(); setInvoiceId(undefined); setReason(""); toast.success(`تم تسجيل ${result.returnNumber} بقيمة ${(result.total / 100).toLocaleString("ar-EG")} ج.م`); }, onError: error => toast.error(error.message || "تعذر تسجيل المرتجع") });
  const submit = () => { if (!invoiceId) return; const items = Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([invoiceItemId, quantity]) => ({ invoiceItemId: Number(invoiceItemId), quantity, reason: reason || undefined })); if (!items.length) return toast.error("حدد كمية مرتجعة واحدة على الأقل"); issueReturn.mutate({ invoiceId, refundCashAccountId: refundAccountId, reason: reason || undefined, items }); };
  return <section className="returns-layout"><section className="erp-panel returns-form"><div className="panel-title"><span><RotateCcw size={16} />تسجيل مرتجع مبيعات</span></div><label>فاتورة البيع<select value={invoiceId ?? ""} onChange={event => setInvoiceId(event.target.value ? Number(event.target.value) : undefined)}><option value="">اختر الفاتورة</option>{invoicesQuery.data?.map(invoice => <option key={invoice.id} value={invoice.id}>{invoice.invoiceNumber} · {(invoice.grandTotal / 100).toLocaleString("ar-EG")} ج.م</option>)}</select></label><label>سبب المرتجع<input value={reason} onChange={event => setReason(event.target.value)} placeholder="مثال: عيب في المنتج" /></label><label>خزنة الاسترداد<select value={refundAccountId ?? ""} onChange={event => setRefundAccountId(event.target.value ? Number(event.target.value) : undefined)}><option value="">بدون استرداد نقدي</option>{accountsQuery.data?.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><p>يرجع النظام الكمية إلى المستودع ويعكس رصيد الخزنة عند اختيارها.</p></section><section className="erp-panel return-items"><div className="panel-title"><span>أصناف الفاتورة</span></div>{!invoiceId ? <p className="empty-state">اختر فاتورة لعرض الأصناف القابلة للإرجاع.</p> : detailsQuery.isLoading ? <p className="empty-state">جارٍ تحميل الأصناف...</p> : <><table className="erp-table records-table"><thead><tr><th>الصنف</th><th>المباع</th><th>سعر الوحدة</th><th>كمية المرتجع</th></tr></thead><tbody>{detailsQuery.data?.items.map(item => <tr key={item.id}><td>{item.productName}</td><td>{item.quantity}</td><td className="amount">{(item.unitPrice / 100).toLocaleString("ar-EG")} ج.م</td><td><input className="return-quantity" min="0" max={item.quantity} type="number" value={quantities[item.id] ?? 0} onChange={event => setQuantities(current => ({ ...current, [item.id]: Math.min(item.quantity, Math.max(0, Number(event.target.value))) }))} /></td></tr>)}</tbody></table><button className="erp-button erp-button--green" disabled={issueReturn.isPending} onClick={submit}>تأكيد المرتجع</button></>}</section></section>;
}
